generate reference until unique value fixes AB#750
AMPnet/wallet-service pull request #87
Opened 2021-01-25 15:44 UTC by josipkoncurat

2021-01-25 16:05 UTC, githinho requested changes
Add a test case.

2021-01-26 08:05 UTC, githinho commented
> Add a test case.

Test not needed

2021-01-26 08:52 UTC, josipkoncurat commented
It would be hard to test this since reference is not a dependency.

2021-01-26 09:34 UTC, githinho approved these changes

2021-01-26 09:34 UTC, merged